export const marketPlace = [
  {
    id: 1,
    imageUrl: "./Images/house1.png",
    title: "Fully Furnished Bungalow",
    price: 48000000,
    specs: [{ beds: 4, bath: 4, toilets: 4 }],
    location: "No. 85, Majeed Aliyu Street, Asa Dam, Ilorin",
  },
  {
    id: 2,
    imageUrl: "./Images/house5.png",
    title: "Modern Fully Detached Duplex",
    price: 300000000,
    specs: [{ beds: 5, bath: 5, toilets: 6 }],
    location: "No. 40 Dayo Shittu Street, Ilorin",
  },
  {
    id: 3,
    imageUrl: "./Images/house4.png",
    title: "Brand New Automated Duplex",
    price: 300000000,
    specs: [{ beds: 6, bath: 6, toilets: 8 }],
    location: "No. 10, Hakeemat Street,GRA, Ilorin",
  },
  {
    id: 4,
    imageUrl: "./Images/house2.png",
    title: "Fully Automated Luxury Duplex",
    price: 135000000,
    specs: [{ beds: 4, bath: 4, toilets: 4 }],
    location: "No. 8 Zazoo Street, Offa Road.",
  },
  {
    id: 5,
    imageUrl: "./Images/house6.png",
    title: "Luxury Mansion ",
    price: 1000000000,
    specs: [{ beds: 8, bath: 8, toilets: 10 }],
    location: "No. 69 Excado Street, London.",
  },
  {
    id: 6,
    imageUrl: "./Images/house3.png",
    title: "Modern Semi Detached Duplex",
    price: 120000000,
    specs: [{ beds: 5, bath: 5, toilets: 6 }],
    location: "No. 105, Sapa Street, Ilorin",
  },
];
